---
title: "Ma_Andrew_Report 4"
output:
  pdf_document: default
---
<h3> Introduction of Paper </h3>
This is my paper for the Credit Card Acceptance Rate. This document includes all the work I have done up to the fourth report. I have incorporated the comments from the first three reports. 
```{r}
library(keras)
library(ISLR)
library(dplyr)
library(AER)
library(tensorflow)
data("CreditCard")
CreditCard = data.frame(CreditCard)
CreditCard$card <- ifelse(CreditCard$card=="yes", 1, 0)
CreditCard$owner <- ifelse(CreditCard$owner=="yes", 1, 0)
CreditCard$selfemp <- ifelse(CreditCard$selfemp=="yes", 1, 0)
```

```{r}
set.seed(1) # we are going to change the seed later to see what happens! It's '1' for now.
card_train = CreditCard %>%
  sample_frac(.7)
card_test = CreditCard %>%
  setdiff(card_train)
```

```{r}
train_labels <- as.matrix(card_train[,"card"]) # This is the Y variable
train_data <- as.matrix(card_train[!names(card_train) %in% c("card")]) #These are the X variables
test_data <- as.matrix(card_test[!names(card_train) %in% c("card")]) #These are the X variables
test_labels <- as.matrix(card_test[,"card"]) # This is the Y variable
```

```{r}
paste0("Training entries: ", length(train_data), ", labels: ", length(train_labels))
```

```{r}
train_data[1:2, ]
```

```{r}
train_data <- scale(train_data) 
test_data <- scale(test_data)
```

```{r}
model <- keras_model_sequential() %>%
  layer_dense(units = 64, activation = "sigmoid", 
              input_shape = dim(train_data)[2]) %>% 
  layer_dense(units = 64, activation = "sigmoid") %>%
  layer_dense(units = 1)
```

```{r}
model %>% compile(
  optimizer = optimizer_rmsprop(),
  loss = loss_binary_crossentropy,
  metrics = metric_binary_accuracy
  #loss = "mse",
  #optimizer = optimizer_rmsprop(),
  #metrics = list("mean_absolute_error")
)
```

```{r}
#model %>% summary()
summary(model)
```

```{r message = FALSE}
epochs <- 200
history <- model %>% fit(
  train_data,
  train_labels,
  epochs = epochs,
  validation_split = 0.2
)
```

#```{r}
#library(ggplot2)
#plot(history, metrics = "mean_absolute_error", smooth = FALSE) +
#  coord_cartesian(ylim = c(0, 5))
#```

```{r}
model %>% summary()
```

```{r}
model <- keras_model_sequential() %>%
  layer_dense(units = 64, activation = "sigmoid",
              input_shape = dim(train_data)[2]) %>%
  layer_dense(units = 64, activation = "sigmoid") %>%
  layer_dense(units = 1)
```

```{r}
model %>% compile(
  loss = "mse",
  optimizer = optimizer_rmsprop(),
  metrics = list("mean_absolute_error")
)
```

```{r}
early_stop <- callback_early_stopping(monitor = "val_loss", patience = 20)
```

```{r}
history2 <- model %>% fit(
  train_data,
  train_labels,
  epochs = epochs,
  validation_split = 0.2,
  callbacks = list(early_stop)
)
```

```{r}
plot(history2, metrics = "mean_absolute_error", smooth = FALSE) +
  coord_cartesian(xlim = c(0, 150), ylim = c(0, 5))
```

```{r}
test_predictions <- model %>% predict(test_data)
mean((test_labels - test_predictions)^2)
```

```{r}
CreditCard$card_high <- ifelse(CreditCard$card > mean(CreditCard$card),1,0)
CreditCard$card_high[1:10]
```

```{r}
set.seed(2) 
card_train = CreditCard %>%
  sample_frac(.7)

card_test = CreditCard %>%
  setdiff(card_train)
```

```{r}
train_labels <- to_categorical(card_train[,"card_high"],2)
train_data <- as.matrix(card_train[!names(card_train) %in% c("card","card_high")])
test_data <- as.matrix(card_test[!names(card_train) %in% c("card","card_high")])
test_labels <- to_categorical(card_test[,"card_high"])
```

```{r}
model <- keras_model_sequential() %>%
  layer_dense(units = 64, activation = "softmax",
              input_shape = dim(train_data)[2]) %>%
  layer_dense(units = 64, activation = "softmax") %>%
  layer_dense(units = 2, activation= "softmax")
```

```{r}
model %>% compile(
  loss = 'categorical_crossentropy',
  optimizer = optimizer_rmsprop(),
  metrics = c('accuracy')
)
```

```{r}
early_stop <- callback_early_stopping(monitor = "val_loss", patience = 20)

epochs=300
history_class <- model %>% fit(
  train_data,
  train_labels,
  epochs = epochs,
  validation_split = 0.2,
  callbacks = list(early_stop)
)
```

```{r}
plot(history_class)
```

```{r}
test_predictions <- model %>% predict(test_data)
head(test_predictions)
```

```{r}
test_class <- model %>% predict_classes(test_data)
head(test_class)
```

```{r}
table(test_labels[,2], test_class)
```